apiVersion: apps/v1

kind: Deployment
metadata:
    name: frontend
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: yurti/streetcode_cli
                  env:
                    - name: REACT_APP_BACKEND_URL
                      value: http://backend-service:5001/api
                  ports:
                    - containerPort: 3000
