name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Test-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Apply the manifests
        run: kubectl apply -f ./backend && kubectl apply -f ./frontend && kubectl apply -f ./mssql
        

